### PR TITLE
Update Cause.js

### PR DESCRIPTION
**Pull request by jacobp100**

### CODE REVIEW

**Comment by rodinhart** [comment]
I feel core libraries should not have try-catch in them, and even if they do for better logging purposes, it should not swallow the error. I would rather find out why this error doesn't bubble up into console (assuming that's the issue?).

**Comment by jacobp100** [comment]
We could make it a development-only try-catch?

**Comment by rodinhart** [comment]
Not worried about perf hit, just correctness.

If React is swallowing the error, we need to switch that off I think, especially in dev.

**Comment by jacobp100** [comment]
You can only catch component errors in React 16, which won't be ready for some time

**Pull request closed without merging**
